name: PR Validation

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: go mod tidy

      # Format code with go fmt
      - name: Check code formatting using gofmt
        uses: Jerome1337/gofmt-action@v1.0.5

      - name: Build project
        run: go build -o GoUp
